const mongoose = require("mongoose");

const Place = mongoose.model(
  "Place",
  new mongoose.Schema({
    name: String,
    address: String 
  }) // leaving out placesId because it should get generated by the database.
);

module.exports = Place;